### ISSUE TITLE
How do I uninstall

### ISSUE THREAD

**Issue by mrbm** [attdevsupport/VideoOptimzer#10]
I am noticing files in various location that I think are related to this app...

what is the proper way to remove this app and all related files it wrote.

thanks

**Comment by bn153x** [comment]
Video Optimizer creates a folder in the users home folder called ‘VideoOptimizerLibrary’
Other folders may contain trace recordings of phones, these are ‘VideoOptimizerAndroid’ and or ‘VideoOptimizerTraceIOS’
VideoOptimizer installation is reported when installing, and allows for the user to override. If you have a desktop link you can follow it to the installation location.

You can delete all of these in any order.

BARRY NELSON
Developer for AT&T
 Video Optimizer

P: 425-288-5159
bn153x@att.com<mailto:bn153x@att.com>

On Feb 25, 2018, at 10:42 AM, mrbm <notifications@github.com<mailto:notifications@github.com>> wrote:


I am noticing files in various location that I think are related to this app...

what is the proper way to remove this app and all related files it wrote.

thanks
