### ISSUE TITLE
Data Collector

### ISSUE THREAD

**Issue by ekreutz** [attdevsupport/VideoOptimzer#4]
Hey,

I'm looking into collecting data from iOS devices and found this library in the process.
It seems that your "datacollectors" might have some of the features I need.

After a quick overview, _some vague questions_ about your data collection for iOS:
- What kind of data do you collect? For instance, is it possible to access process-level memory allocation data? Basically: a timeline of of the total memory allocation size for my app.
- What about iOS11 support? It's just around the corner.

Looking forward to hearing back from you.

Interesting project,
Emil

**Comment by dougsillars** [comment]
Emil, 

Video Optimizer collects network traffic on iOS and Android devices.  It does not examine any device memory.

OS 11 works fine - we are ironing out an issue with video capture (where we capture the screen of the phone while the network capture is occurring).

Thank you, 

Doug
