### ISSUE TITLE
Any command line capability?

### ISSUE THREAD

**Issue by hqfking** [attdevsupport/VideoOptimzer#5]
In the latest 1.2.1, there is a doc for command line but no actual zip file mentioned in the doc. 

How can I find some help for command line capability.  It would be helpful to be automated some testing steps.

**Comment by ls661n** [comment]
Hi hqfking,

May I know which doc you are referring to? We would like to help you.
Thank you!

**Comment by hqfking** [comment]
It is file called ATT_ARO_Command_Line_Interface User_Guide-DRAFT.pdf which
is located in C:\Program Files\VideoOptimizer\Documentation.

I attached one copy for your reference.

**Comment by dougsillars** [comment]
hqfking

There are also docs on the webpage: developer.att.com/VideoOptimizer

On you mac - the command line is inside the tool:  
![image](https://user-images.githubusercontent.com/1514288/31151132-2898f436-a864-11e7-8601-c80240340ac8.png)

The shell script has pretty good help (-h) 

Doug

**Comment by hqfking** [comment]
Hi Doug,

I am running the VideoOptimzer on the Windows now.

When I try to run the vo.bat

it gives me the following errors:
Exception in thread "main" java.lang.UnsupportedClassVersionError:
com/att/aro/console/Application : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at
java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at
sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

And my java version is

**Comment by hqfking** [comment]
Hi Doug,

Sorry, the previous email is cut short.

And my java version is
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by dougsillars** [comment]
Sorry you are having issues.  My dev just successfully ran on his windows box.
He has a number of questions:

I think I need to know more about the PC
Windows version
from command line
where java

from environment
PATH
JAVA_HOME

installed apps if yes where:
Wireshark
WinPcap
FFmpeg
VLC media player
Android SDK


Doug

**Comment by hqfking** [comment]
Hi,

Sorry for the delayed response.  Here are the required information:

I think I need to know more about the PC
Windows version:

Win10

where java:

C:\ProgramData\Oracle\Java\javapath\java.exe

C:\Program Files\Java\jdk1.7.0_79\bin\java.exe

C:\Windows\System32\java.exe

from environment
PATH：

C:\ProgramData\Oracle\Java\javapath;%JAVA_HOME%\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program
Files\MathWorks\DevelTools\bin;C:\Program Files\Perforce;C:\Program
Files\Perforce\DVCS\;%M2_HOME%\bin\;%ANDROID_HOME%\platform-tools;C:\Program
Files\MATLAB\R2016b\bin;C:\Program
Files\MATLAB\R2016a\bin;L:\Software\ffmpeg-3.2.4-win64-static\bin;%VLC_PLUGIN_PATH%


JAVA_HOME：

C:\Program Files\Java\jdk1.7.0_79

(The C:\ProgramData\Oracle\Java\javapath which is on the top of the PATH is
pointing to the Java 1.8)


installed apps if yes where:
Wireshark： No
WinPcap:  C:\Program Files (x86)\WinPcap
FFmpeg:  L:\Software\ffmpeg-3.2.4-win64-static\bin
VLC media player:    C:\Program Files (x86)\VideoLAN\VLC
Android SDK:   C:\Users\dhuang\AppData\Local\Android\sdk


Thanks.

David

**Comment by ls661n** [comment]
Hi David,

Sorry for the late.
After I checked with your review, I saw some of the issues about the setting in your computer.
According to your comment on Oct 5, the error message brought up  "Unsupported major.minor version 52.0........"
It means you use the Java 1.7 to run the app which compiled by Java 1.8.
After I reviewed your comment on Oct 11, I suggest you can to set the JAVA_HOME (1.7) for you PATH consistent with you have installed (1.8).
Thanks for your feedback.
Please feel free to relay your comments, suggestions or corrections. 
If you find errors or inaccuracies in the code, please report them to us.

Lindsay
