### ISSUE TITLE
When is the 2.1.2 version available?

### ISSUE THREAD

**Issue by genie-park** [attdevsupport/VideoOptimzer#6]
After I download AT&T Video optimizer binary from AT&T developer site. 
I found out It is different from this open source version.
Do you have any plan to release 2.1.2 version to public?

**Comment by genie-park** [comment]
Hi Doug, 
Thank you for replying so promptly.

When I extract VPNCollector1.2.1.apk in windows version binary, 
I found out it  is different from open source. 
Open source version has no code related to "attenuator". 
![image](https://user-images.githubusercontent.com/27672455/33001017-c7a7d588-cdee-11e7-9dc2-e7d9e4fc1e5d.png)
Will it be resolved in version 1.3?

When I use NorootAndroidCollector in Windows version video optimizer,
I always encounter severe upload network speed degradation (154mpbs to 4.5mbps) 
Will this problem be resolved in 1.3 version?

thanks in advance. 
genie

**Comment by dougsillars** [comment]
Genie,

Unfortunately, the attenuation code (and the secure collection code) is not
a part of the open source.  Is there any reason you cannot use the compiled
version from the developer website?  We do have APIs that you can use to
call these functions.

Doug

Douglass Sillars, PhD
(206) 295-4980

**Comment by ls661n** [comment]
Hi genie-park,

We will release the attenuation module source code in the upcoming  1.3 open source release.
We appreciate your feedback.
Thank you very much!

Lindsay

**Comment by genie-park** [comment]
thank you .  I appreciate it
genie.
